genome: "mm10"
reference_genome: "data/reference_genome/mm10.fa"
bowtie2_index: "data/reference_genome/mm10"
annotation_gtf: "data/reference_genome/Mus_musculus.GRCm38.110.gtf"
samples:
  single:
    - "SRR1979874"
    - "SRR1979880"
    - "SRR1979877"
    - "SRR1979883"
  paired:
    - "SRR5642565"
    - "SRR5642566"
    - "SRR5642568"
    - "SRR5642569"
    - "SRR5642571"
    - "SRR5642572"
