data: "data"
sample: ["SRR5642565", "SRR5642566", "SRR5642568", "SRR5642569", "SRR5642571", "SRR5642572"]
qc_reports: "qc_reports"
trimmed_data: "trimmed"
aligned_data: "aligned"
results: "results"
reference_genome: "data/reference_genome"
hisat2_index: "data/reference_genome/index"
annotation_gtf: "data/reference_genome/annotation.gtf"
